version: '3'

vars:
  BINARY_NAME: cm
  WASM_BINARY: calcmark.wasm
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  BUILD_TIME:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: -s -w -X main.Version={{.VERSION}} -X main.BuildTime={{.BUILD_TIME}}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Testing tasks
  test:
    desc: Run all tests (excludes WASM - use test:wasm for those)
    cmds:
      - go test $(go list ./... | grep -v '/impl/wasm') -v

  test:wasm:
    desc: Run WASM tests (requires wasm build environment)
    cmds:
      - GOOS=js GOARCH=wasm go test ./impl/wasm/... -v

  test:short:
    desc: Run tests in short mode
    cmds:
      - go test ./... -short

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test ./...  -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - echo 'Coverage report generated at coverage.html'

  test:lexer:
    desc: Run lexer tests only
    cmds:
      - go test ./spec/lexer/... -v

  test:parser:
    desc: Run parser tests only
    cmds:
      - go test ./spec/parser/... -v

  test:semantic:
    desc: Run semantic validation tests
    cmds:
      - go test ./spec/semantic/... -v

  test:interpreter:
    desc: Run interpreter tests
    cmds:
      - go test ./impl/interpreter/... -v

  test:integration:
    desc: Run integration tests
    cmds:
      - go test ./spec/document/... -v

  # Build tasks
  build:
    desc: Build CLI for current platform
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o {{.BINARY_NAME}} ./cmd/calcmark
      - echo 'Built {{.BINARY_NAME}}'

  build:all:
    desc: Build for all platforms
    deps:
      - build:linux
      - build:darwin
      - build:windows

  build:linux:
    internal: true
    cmds:
      - mkdir -p dist
      - GOOS=linux GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o dist/{{.BINARY_NAME}}-linux-amd64 ./cmd/calcmark
      - GOOS=linux GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o dist/{{.BINARY_NAME}}-linux-arm64 ./cmd/calcmark
      - echo 'Built Linux binaries'

  build:darwin:
    internal: true
    cmds:
      - mkdir -p dist
      - GOOS=darwin GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o dist/{{.BINARY_NAME}}-darwin-amd64 ./cmd/calcmark
      - GOOS=darwin GOARCH=arm64 go build -ldflags "{{.LDFLAGS}}" -o dist/{{.BINARY_NAME}}-darwin-arm64 ./cmd/calcmark
      - echo 'Built macOS binaries'

  build:windows:
    internal: true
    cmds:
      - mkdir -p dist
      - GOOS=windows GOARCH=amd64 go build -ldflags "{{.LDFLAGS}}" -o dist/{{.BINARY_NAME}}-windows-amd64.exe ./cmd/calcmark
      - echo 'Built Windows binary'

  # WASM build tasks
  build:wasm:
    desc: Build WASM binary
    cmds:
      - mkdir -p dist
      - GOOS=js GOARCH=wasm go build -tags wasm -ldflags "{{.LDFLAGS}}" -o dist/{{.WASM_BINARY}} ./cmd/calcmark
      - cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" dist/
      - echo 'Built WASM binary'
      - ls -lh dist/{{.WASM_BINARY}}

  build:wasm:tiny:
    internal: true
    cmds:
      - mkdir -p dist
      - tinygo build -o dist/{{.WASM_BINARY}} -target wasm -no-debug ./cmd/calcmark
      - echo 'Built TinyGo WASM binary'
      - ls -lh dist/{{.WASM_BINARY}}

  # Development tasks
  dev:
    desc: Run in development mode
    cmds:
      - go run ./cmd/calcmark {{.CLI_ARGS}}

  dev:repl:
    desc: Start REPL
    cmds:
      - go run ./cmd/calcmark

  dev:eval:
    desc: Evaluate example file
    cmds:
      - go run ./cmd/calcmark eval examples/dates_and_units.cm

  # Quality tasks
  lint:
    desc: Run basic linters (fmt, vet)
    cmds:
      - go fmt ./...
      - go vet $(go list ./... | grep -v '/impl/wasm')
      - echo '✓ Basic linting passed'

  vet:
    desc: Run go vet with verbose output (excludes WASM)
    cmds:
      - go vet -v $(go list ./... | grep -v '/impl/wasm')

  modernize:
    desc: Run Go modernize analyzer (suggests modern Go idioms)
    cmds:
      - go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest $(go list ./... | grep -v '/impl/wasm')
      - echo '✓ Modernize check passed'

  staticcheck:
    desc: Run staticcheck (uses go run, no global install needed)
    cmds:
      - go run honnef.co/go/tools/cmd/staticcheck@latest $(go list ./... | grep -v '/impl/wasm')
      - echo '✓ Staticcheck passed'

  lint:strict:
    desc: Run golangci-lint (install from https://golangci-lint.run/usage/install/)
    cmds:
      - golangci-lint run ./...
      - echo '✓ Golangci-lint passed'

  quality:
    desc: Run all quality checks (recommended before commit)
    cmds:
      - task: lint
      - task: modernize
      - task: staticcheck
      - echo '✓ All quality checks passed'

  quality:full:
    desc: Run complete quality gate including strict linting
    cmds:
      - task: lint
      - task: staticcheck
      - task: lint:strict
      - task: test
      - echo '✓ Full quality gate passed'

  security:
    desc: Run security-focused tests
    cmds:
      - go test -v -run TestFileSizeLimit ./cmd/calcmark
      - go test -v -run TestPathValidation ./cmd/calcmark
      - echo '✓ Security tests passed (add more as implemented)'

  # Benchmark tasks  
  bench:
    desc: Run benchmarks
    cmds:
      - go test ./... -bench=. -benchmem

  bench:lexer:
    desc: Benchmark lexer
    cmds:
      - go test ./spec/lexer/... -bench=. -benchmem

  bench:parser:
    desc: Benchmark parser
    cmds:
      - go test ./spec/parser/... -bench=. -benchmem

  # Clean tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -rf dist/
      - rm -f coverage.out coverage.html
      - go clean -cache

  # Install task
  install:
    desc: Install to GOPATH/bin
    cmds:
      - go install -ldflags "{{.LDFLAGS}}" ./cmd/calcmark

  # Dependency tasks
  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  deps:update:
    desc: Update dependencies
    cmds:
      - go get -u ./...
      - go mod tidy

  # Example/Demo tasks
  example:dates:
    internal: true
    cmds:
      - echo "today + 7 days" | ./{{.BINARY_NAME}} eval
      - echo "Dec 25 2025 + 30 days" | ./{{.BINARY_NAME}} eval

  example:units:
    internal: true
    cmds:
      - echo "5 kg + 10 lb" | ./{{.BINARY_NAME}} eval
      - echo "10 meters + 5 feet" | ./{{.BINARY_NAME}} eval

  example:
    desc: Run all examples
    deps:
      - build
    cmds:
      - task: example:dates
      - task: example:units

  # Release task
  release:
    desc: Build release binaries (runs all quality checks first)
    deps:
      - clean
      - test          # All tests must pass
      - vet           # Go vet must pass
      - staticcheck   # Static analysis must pass
      - security      # Security tests must pass
    cmds:
      - task: build:all
      - task: build:wasm
      - echo '✓ All quality checks passed'
      - echo 'Release binaries built in dist/'
