// Command doceval scans Hugo markdown files for ```calcmark code blocks,
// evaluates each through the CalcMark interpreter, and writes the results to
// site/data/cm_results.json. Hugo's render-codeblock-calcmark.html render hook
// reads this file to display inline results alongside code blocks.
//
// Pages with `calcmark_build: progressive` in Hugo frontmatter evaluate all
// ```calcmark blocks in a shared interpreter context so variables carry across
// blocks. The default (`standalone`) evaluates each block independently.
//
// Pages with `calcmark_source: <path>` in Hugo frontmatter trigger full-document
// generation: the referenced .cm file is evaluated and rendered as Markdown,
// then written as a sibling full.md page under the same directory.
//
// Invoked by `task generate-docs` before Hugo builds the site.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/CalcMark/go-calcmark/format"
	"github.com/CalcMark/go-calcmark/format/display"
	implDoc "github.com/CalcMark/go-calcmark/impl/document"
	"github.com/CalcMark/go-calcmark/spec/document"
)

// BlockResult holds the evaluated results for a single ```calcmark code block.
type BlockResult struct {
	Lines []LineResult `json:"lines"`
	Error string       `json:"error,omitempty"`
}

// LineResult pairs a source line with its display-formatted result.
type LineResult struct {
	Source   string `json:"source"`
	Result   string `json:"result,omitempty"`
	IsBlank  bool   `json:"is_blank,omitempty"`
	Variable string `json:"variable,omitempty"`
}

// generatedMarker is written into the Hugo frontmatter of generated full.md
// files so doceval can skip them on subsequent runs.
const generatedMarker = "# generated by doceval — do not edit"

func run() error {
	contentDir := filepath.Join("site", "content")

	// Find all .md files under site/content/, skipping generated files.
	var mdFiles []string
	err := filepath.Walk(contentDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".md") {
			mdFiles = append(mdFiles, path)
		}
		return nil
	})
	if err != nil {
		return fmt.Errorf("walk %s: %w", contentDir, err)
	}

	results := make(map[string]BlockResult)
	df := display.DefaultFormatter()
	var evalErrors []string

	// Track pages that declare a calcmark_source for full-doc generation.
	type fullDocJob struct {
		mdFile string
		source string // calcmark_source path (repo-relative)
		title  string // Hugo page title
	}
	var fullDocJobs []fullDocJob

	for _, mdFile := range mdFiles {
		data, err := os.ReadFile(mdFile)
		if err != nil {
			return fmt.Errorf("read %s: %w", mdFile, err)
		}

		content := string(data)

		// Skip files generated by a previous doceval run.
		if isGenerated(content) {
			continue
		}

		blocks := extractCMBlocks(content)

		// Collect full-doc jobs regardless of whether the page has blocks.
		if src := calcmarkSource(content); src != "" {
			fullDocJobs = append(fullDocJobs, fullDocJob{
				mdFile: mdFile,
				source: src,
				title:  hugoTitle(content),
			})
		}

		if len(blocks) == 0 {
			continue
		}

		mode := calcmarkBuildMode(content)

		if mode == "progressive" {
			errs := evalProgressive(content, blocks, results, df)
			for _, e := range errs {
				evalErrors = append(evalErrors, fmt.Sprintf("  %s: %s", mdFile, e))
			}
		} else {
			// Standalone: each block is an independent document.
			// Errors are recorded in JSON but don't fail the build
			// (blocks may demo frontmatter features that aren't available).
			for _, block := range blocks {
				key := hashKey(block)
				if _, exists := results[key]; exists {
					continue
				}
				results[key] = evalBlockIndependent(block, df)
			}
		}
	}

	// --- Phase 2: Generate full-document pages from calcmark_source ---
	fullDocCount := 0
	for _, job := range fullDocJobs {
		if err := generateFullDoc(job.mdFile, job.source, job.title); err != nil {
			evalErrors = append(evalErrors, fmt.Sprintf("  %s: full-doc: %s", job.mdFile, err))
		} else {
			fullDocCount++
		}
	}

	outPath := filepath.Join("site", "data", "cm_results.json")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("create data dir: %w", err)
	}

	jsonData, err := json.MarshalIndent(results, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal JSON: %w", err)
	}

	if err := os.WriteFile(outPath, jsonData, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	fmt.Printf("Generated %s (%d blocks from %d files)\n", outPath, len(results), len(mdFiles))
	if fullDocCount > 0 {
		fmt.Printf("Generated %d full-document page(s)\n", fullDocCount)
	}

	if len(evalErrors) > 0 {
		fmt.Fprintf(os.Stderr, "\n%d evaluation error(s):\n", len(evalErrors))
		for _, e := range evalErrors {
			fmt.Fprintln(os.Stderr, e)
		}
		return fmt.Errorf("%d block(s) failed evaluation", len(evalErrors))
	}

	return nil
}

// generateFullDoc reads a .cm file, evaluates it, and writes a Hugo-compatible
// full.md page alongside the parent page's index.md.
func generateFullDoc(parentMD, cmSource, parentTitle string) error {
	data, err := os.ReadFile(cmSource)
	if err != nil {
		return fmt.Errorf("read %s: %w", cmSource, err)
	}

	doc, err := document.NewDocument(string(data))
	if err != nil {
		return fmt.Errorf("parse %s: %w", cmSource, err)
	}

	eval := implDoc.NewEvaluator()
	if err := eval.Evaluate(doc); err != nil {
		return fmt.Errorf("eval %s: %w", cmSource, err)
	}

	var body bytes.Buffer
	mdFormatter := &format.MarkdownFormatter{}
	opts := format.Options{FrontmatterAsCodeFence: true}
	if err := mdFormatter.Format(&body, doc, opts); err != nil {
		return fmt.Errorf("format %s: %w", cmSource, err)
	}

	// Build the output page with Hugo frontmatter.
	title := parentTitle
	if title == "" {
		title = "Full Document"
	} else {
		title += " — Full Document"
	}

	var page bytes.Buffer
	fmt.Fprintf(&page, "---\ntitle: %q\n%s\nbuild:\n  list: never\n---\n\n", title, generatedMarker)
	page.Write(body.Bytes())

	// Write to full.md in the same directory as the parent page.
	outDir := filepath.Dir(parentMD)
	outPath := filepath.Join(outDir, "full.md")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, err)
	}

	return os.WriteFile(outPath, page.Bytes(), 0o644)
}

// calcmarkBuildMode reads the Hugo frontmatter and returns the value of
// calcmark_build ("progressive" or "standalone"). Defaults to "standalone".
func calcmarkBuildMode(content string) string {
	scanner := bufio.NewScanner(strings.NewReader(content))

	// Hugo frontmatter starts with ---
	if !scanner.Scan() || strings.TrimSpace(scanner.Text()) != "---" {
		return "standalone"
	}

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "---" {
			break
		}
		if val, ok := strings.CutPrefix(line, "calcmark_build:"); ok {
			if strings.TrimSpace(val) == "progressive" {
				return "progressive"
			}
		}
	}

	return "standalone"
}

// calcmarkSource reads the Hugo frontmatter and returns the value of
// calcmark_source (a repo-relative path to a .cm file). Returns "" if absent.
func calcmarkSource(content string) string {
	return hugoFrontmatterValue(content, "calcmark_source:")
}

// hugoTitle reads the Hugo frontmatter and returns the page title. Returns "" if absent.
func hugoTitle(content string) string {
	return hugoFrontmatterValue(content, "title:")
}

// isGenerated returns true if the content was generated by doceval.
func isGenerated(content string) bool {
	return strings.Contains(content, generatedMarker)
}

// hugoFrontmatterValue extracts a single value from Hugo YAML frontmatter.
// It handles bare values and double-quoted values.
func hugoFrontmatterValue(content, key string) string {
	scanner := bufio.NewScanner(strings.NewReader(content))

	// Hugo frontmatter starts with ---
	if !scanner.Scan() || strings.TrimSpace(scanner.Text()) != "---" {
		return ""
	}

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "---" {
			break
		}
		if val, ok := strings.CutPrefix(line, key); ok {
			val = strings.TrimSpace(val)
			// Strip surrounding double quotes
			if len(val) >= 2 && val[0] == '"' && val[len(val)-1] == '"' {
				val = val[1 : len(val)-1]
			}
			return val
		}
	}

	return ""
}

// evalProgressive evaluates all calcmark blocks in a shared interpreter context.
// Returns a list of error strings (empty on success).
func evalProgressive(content string, blocks []string, results map[string]BlockResult, df display.Formatter) []string {
	// Extract CalcMark frontmatter from ```yaml blocks in the markdown
	frontmatter := extractCMFrontmatter(content)

	// Concatenate all blocks into a single CalcMark document
	combined := frontmatter + strings.Join(blocks, "\n\n")

	doc, err := document.NewDocument(combined)
	if err != nil {
		return []string{fmt.Sprintf("parse error: %s", err)}
	}

	eval := implDoc.NewEvaluator()
	if err := eval.Evaluate(doc); err != nil {
		return []string{fmt.Sprintf("eval error: %s", err)}
	}

	// Build a source-line → result map from the evaluated document.
	// The interpreter classifies lines into CalcBlock/TextBlock, which may
	// split a raw code block differently than the original source. We use
	// exact source-line matching to map results back, avoiding index drift.
	type lineResult struct {
		result   string
		variable string
	}
	resultBySource := make(map[string]lineResult)

	for _, node := range doc.GetBlocks() {
		if cb, ok := node.Block.(*document.CalcBlock); ok {
			for _, stmt := range format.AlignResults(cb) {
				if stmt.Result != nil && strings.TrimSpace(stmt.Source) != "" {
					resultBySource[strings.TrimSpace(stmt.Source)] = lineResult{
						result:   df.Format(stmt.Result),
						variable: stmt.Variable,
					}
				}
			}
		}
	}

	// Map results back to individual blocks by matching source lines
	for _, block := range blocks {
		key := hashKey(block)
		if _, exists := results[key]; exists {
			continue
		}

		lines := strings.Split(block, "\n")
		var lineResults []LineResult
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			lr := LineResult{Source: line, IsBlank: trimmed == ""}
			if r, ok := resultBySource[trimmed]; ok {
				lr.Result = r.result
				lr.Variable = r.variable
			}
			lineResults = append(lineResults, lr)
		}
		results[key] = BlockResult{Lines: lineResults}
	}

	return nil
}

// evalBlockIndependent evaluates a single code block as a standalone document.
func evalBlockIndependent(source string, df display.Formatter) BlockResult {
	doc, err := document.NewDocument(source)
	if err != nil {
		return BlockResult{Error: err.Error()}
	}

	eval := implDoc.NewEvaluator()
	if err := eval.Evaluate(doc); err != nil {
		return BlockResult{Error: err.Error()}
	}

	var lineResults []LineResult
	for _, node := range doc.GetBlocks() {
		switch block := node.Block.(type) {
		case *document.CalcBlock:
			stmts := format.AlignResults(block)
			for _, stmt := range stmts {
				lr := LineResult{Source: stmt.Source, IsBlank: stmt.IsBlank, Variable: stmt.Variable}
				if stmt.Result != nil {
					lr.Result = df.Format(stmt.Result)
				}
				lineResults = append(lineResults, lr)
			}
		case *document.TextBlock:
			for _, line := range block.Source() {
				lineResults = append(lineResults, LineResult{
					Source:  line,
					IsBlank: strings.TrimSpace(line) == "",
				})
			}
		}
	}

	return BlockResult{Lines: lineResults}
}

// extractCMFrontmatter scans for ```yaml blocks containing CalcMark
// frontmatter (exchange rates, globals, scale, convert_to) and returns
// them as a combined CalcMark frontmatter string prefixed to the document.
func extractCMFrontmatter(markdown string) string {
	lines := strings.Split(markdown, "\n")
	var yamlBlocks []string

	inYaml := false
	var current []string

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !inYaml {
			if trimmed == "```yaml" {
				inYaml = true
				current = nil
			}
		} else if trimmed == "```" {
			inYaml = false
			block := strings.Join(current, "\n")
			if strings.Contains(block, "exchange:") || strings.Contains(block, "globals:") ||
				strings.Contains(block, "scale:") || strings.Contains(block, "convert_to:") {
				block = strings.TrimSpace(block)
				block = strings.TrimPrefix(block, "---")
				block = strings.TrimSuffix(block, "---")
				block = strings.TrimSpace(block)
				if block != "" {
					yamlBlocks = append(yamlBlocks, block)
				}
			}
			current = nil
		} else {
			current = append(current, line)
		}
	}

	if len(yamlBlocks) == 0 {
		return ""
	}
	return "---\n" + strings.Join(yamlBlocks, "\n") + "\n---\n"
}

// extractCMBlocks pulls all ```calcmark fenced code block contents from markdown.
func extractCMBlocks(markdown string) []string {
	var blocks []string
	lines := strings.Split(markdown, "\n")

	inBlock := false
	var current []string

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if !inBlock {
			if rest, ok := strings.CutPrefix(trimmed, "```calcmark"); ok {
				if rest == "" || rest[0] == '{' || rest[0] == ' ' {
					inBlock = true
					current = nil
					continue
				}
			}
		} else {
			if trimmed == "```" {
				inBlock = false
				blocks = append(blocks, strings.Join(current, "\n"))
				current = nil
			} else {
				current = append(current, line)
			}
		}
	}

	return blocks
}

// hashKey produces a stable SHA-256 hash of a code block's content,
// used as the lookup key in cm_results.json.
func hashKey(content string) string {
	lines := strings.Split(content, "\n")
	for i := range lines {
		lines[i] = strings.TrimRight(lines[i], " \t")
	}
	normalized := strings.TrimSpace(strings.Join(lines, "\n"))
	h := sha256.Sum256([]byte(normalized))
	return fmt.Sprintf("%x", h)
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "doceval: %v\n", err)
		os.Exit(1)
	}
}
